import Head from "next/head";

import Navbar from "src/components/Navbar";
import Hero from "src/components/Hero";

import * as FaIcons from "react-icons/fa";

export default function Home() {
  return (
    <div className=" ">
      <Head>
        <title>Software Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-sl.png" />
      </Head>

      <main className=" relative" style={{ height: 2000 }}>
        <section className="Head">
          {/* fixed top-0 right-0 left-0 z-50 */}
          <div className="container mx-auto px-6 lg:px-0">
            <Navbar></Navbar>

            <Hero></Hero>
          </div>
        </section>

        {/* <div className="elips "></div> */}
      </main>
    </div>
  );
}
