import React from "react";
import Head from "next/head";
import Link from "next/link";

import LogoBrand from "public/images/icon-sl.svg";

export default function Register() {
  return (
    <>
      <Head>
        <title>Software Library | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo-sl.png" />
      </Head>

      <main>
        <section className=" w-screen h-screen  flex items-center">
          <div className="container mx-auto px-6 pt-20 lg:px-0">
            <div className=" lg:flex items-center w-full lg:h-640">
              <div className=" md:w-472 lg:w-3/5  lg:h-full flex lg:items-center justify-center mx-auto">
                <img
                  src="/images/img-hero-login.png"
                  alt=""
                  className=" w-full object-cover"
                />
              </div>

              <div className=" lg:w-2/5 my-auto">
                <div className=" md:w-3/5 mx-auto mt-12 lg:mt-0">
                  <div className="flex items-center justify-center ">
                    <LogoBrand className=""></LogoBrand>
                    <span className="ml-4 text-2xl text-slIndigo-600 font-bold text-center leading-none mr-14 font-sans">
                      Software <br /> Library
                    </span>
                  </div>
                  <form action="" className="mt-14">
                    <label class="block ">
                      <span class="text-gray-800 font-semibold text-lg">
                        Nama
                      </span>
                      <input
                        type="text"
                        placeholder="Your name"
                        class="p-1 mt-1 text-gray-600 font-semibold bg-transparent  border-b-2 border-gray-300 outline-none focus:border-slIndigo-600  focus:outline-purple focus:border-slPurple w-full transition-all duration-300"
                      />
                      <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                        Invalid name !
                      </span>
                    </label>
                    <label class="block mt-6">
                      <span class="text-gray-800 font-semibold text-lg">
                        Email
                      </span>
                      <input
                        type="email"
                        placeholder="example@gmail.com"
                        class="p-1 mt-1 text-gray-600 font-semibold bg-transparent  border-b-2 border-gray-300 outline-none focus:border-slIndigo-600  focus:outline-purple focus:border-slPurple w-full transition-all duration-300"
                      />
                      <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                        wrong email !
                      </span>
                    </label>
                    <label class="block mt-6">
                      <span class="text-gray-800 font-semibold text-lg">
                        Password
                      </span>
                      <input
                        type="password"
                        placeholder="*********"
                        class="p-1 mt-1 text-gray-600 font-semibold bg-transparent  border-b-2 border-gray-300 outline-none focus:border-slIndigo-600  focus:outline-purple focus:border-slPurple w-full transition-all duration-300"
                      />
                      <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                        wrong password !
                      </span>
                    </label>

                    <button
                      type="submit"
                      className="mt-8 w w-full py-3 rounded-lg bg-slIndigo-600 text-white font-semibold font-sans text-xl shadow-md hover:bg-slIndigo-800 hover:shadow-xl transition-all duration-300"
                    >
                      Register Now
                    </button>

                    <div className="my-10">
                      Already have an account?{" "}
                      <Link href="/login">
                        <a className=" text-slIndigo-600 cursor-pointer hover:underline hover:text-slIndigo-400 font-semibold">
                          Login
                        </a>
                      </Link>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
